version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
    depends_on:
      - nats

  messaging-service:
    build:
      context: .
      dockerfile: apps/messaging-service/Dockerfile
    container_name: messaging-service
    ports:
      - "4002:4002"
    environment:
      PORT: 4002

  mission-service:
    build:
      context: .
      dockerfile: apps/mission-service/Dockerfile
    container_name: mission-service
    ports:
      - "4003:4003"
    environment:
      PORT: 4003

  candidature-service:
    build:
      context: .
      dockerfile: apps/candidature-service/Dockerfile
    container_name: candidature-service
    ports:
      - "4004:4004"
    environment:
      PORT: 4004
    depends_on:
      - rabbitmq

  indep-api:
    build:
      context: .
      dockerfile: apps/indep-api/Dockerfile
    container_name: indep-api
    ports:
      - "3002:3000"
    environment:
      PORT: 3000
    depends_on:
      - auth-service
      - messaging-service
      - mission-service
      - candidature-service

  indep-front:
    build:
      context: .
      dockerfile: apps/indep-front/Dockerfile
    container_name: indep-front
    ports:
      - "3001:3000"
    depends_on:
      - indep-api

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"

  minio:
    image: minio/minio
    container_name: indep-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 admin password123;
      mc mb myminio/cv-bucket;
      mc policy set public myminio/cv-bucket;
      exit 0;
      "

volumes:
  minio-data:
