# Builder
FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

RUN corepack enable && pnpm install
RUN pnpm --filter=mission-service build

# Final
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/apps/mission-service/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

CMD ["node", "dist/main.js"]


EXPOSE 4003
