# Stage 1 : Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY constants.ts ./constants.ts
COPY apps ./apps


RUN corepack enable && pnpm install --no-frozen-lockfile
RUN pnpm --filter=auth-service build

# Stage 2 : Run
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/apps/auth-service/dist ./dist
COPY --from=builder /app/apps/auth-service/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/constants.ts ./constants.ts

CMD ["node", "dist/main"]
